export const dataTypeList = [
  {
    code: "date",
    name: "日期",
    lengthFlag: false,
    lengthMin: null,
    lengthMax: null,
    precisionFlag: false,
    precisionMin: null,
    precisionMax: null,
    id: "DT-01",
  },
  {
    code: "timestamp",
    name: "时间戳",
    lengthFlag: false,
    lengthMin: null,
    lengthMax: null,
    precisionFlag: false,
    precisionMin: null,
    precisionMax: null,
    id: "DT-02",
  },
  {
    code: "varchar",
    name: "字符串",
    lengthFlag: true,
    lengthMin: 0,
    lengthMax: 10485760,
    precisionFlag: false,
    precisionMin: null,
    precisionMax: null,
    id: "DT-03",
  },
  {
    code: "int4",
    name: "整数",
    lengthFlag: false,
    lengthMin: null,
    lengthMax: null,
    precisionFlag: false,
    precisionMin: null,
    precisionMax: null,
    id: "DT-04",
  },
  {
    code: "int8",
    name: "大整数",
    lengthFlag: false,
    lengthMin: null,
    lengthMax: null,
    precisionFlag: false,
    precisionMin: null,
    precisionMax: null,
    id: "DT-05",
  },
  {
    code: "float4",
    name: "单精度浮点数",
    lengthFlag: false,
    lengthMin: null,
    lengthMax: null,
    precisionFlag: false,
    precisionMin: null,
    precisionMax: null,
    id: "DT-06",
  },
  {
    code: "float8",
    name: "双精度浮点数",
    lengthFlag: false,
    lengthMin: null,
    lengthMax: null,
    precisionFlag: false,
    precisionMin: null,
    precisionMax: null,
    id: "DT-07",
  },
  {
    code: "decimal",
    name: "十进制小数",
    lengthFlag: true,
    lengthMin: 1,
    lengthMax: 1000,
    precisionFlag: true,
    precisionMin: 0,
    precisionMax: 1000,
    id: "DT-08",
  },
  {
    code: "bool",
    name: "布尔",
    lengthFlag: false,
    lengthMin: null,
    lengthMax: null,
    precisionFlag: false,
    precisionMin: null,
    precisionMax: null,
    id: "DT-09",
  },
  {
    code: "char",
    name: "字符",
    lengthFlag: true,
    lengthMin: 1,
    lengthMax: 10485760,
    precisionFlag: false,
    precisionMin: null,
    precisionMax: null,
    id: "DT-10",
  },
  {
    code: "text",
    name: "文本",
    lengthFlag: false,
    lengthMin: null,
    lengthMax: null,
    precisionFlag: false,
    precisionMin: null,
    precisionMax: null,
    id: "DT-11",
  },
  {
    code: "json",
    name: "JSON",
    lengthFlag: false,
    lengthMin: null,
    lengthMax: null,
    precisionFlag: false,
    precisionMin: null,
    precisionMax: null,
    id: "DT-12",
  },
  {
    code: "xml",
    name: "XML",
    lengthFlag: false,
    lengthMin: null,
    lengthMax: null,
    precisionFlag: false,
    precisionMin: null,
    precisionMax: null,
    id: "DT-13",
  },
  {
    code: "bytea",
    name: "二进制",
    lengthFlag: false,
    lengthMin: null,
    lengthMax: null,
    precisionFlag: false,
    precisionMin: null,
    precisionMax: null,
    id: "DT-14",
  },
];
